"""add admin notification model

Revision ID: 59a4d0656705
Revises: f7a36a862b82
Create Date: 2024-11-04 06:25:33.047340

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision: str = "59a4d0656705"
down_revision: Union[str, None] = "7c93652ae4b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            pg.ENUM(
                "REGISTRATION",
                "REFRESH_TOKEN_UPDATE",
                "LIKE",
                "SERIES",
                "NEW_FILMS",
                "NEWS",
                "SALE",
                "PROMOTION",
                name="eventtypesenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            pg.ENUM("EMAIL", "WEBSOCKET", name="channelenum", create_type=False),
            nullable=False,
        ),
        sa.Column("filter", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            pg.ENUM(
                "INIT",
                "IN_PROGRESS",
                "SUCCESS",
                "FAILED",
                name="notificationtaskstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("send_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_notifications")
    # ### end Alembic commands ###
