name: Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11",]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt 
          
      - name: Check flake8
        run: |
          flake8 notification_api

      - name: Check mypy
        run: |
          mypy notification_api

      - name: Check black
        run: |
          black --check notification_api 

      - name: Check isort
        run: |
          isort --check notification_api     

  notify:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Repository: ${{ github.repository }}
            🔖 Commit: ${{ github.sha }}
            👤 Author: ${{ github.actor }}
            
            ${{#if success()}}
            🎉 The pipeline completed **successfully**! Good job! ✅
            ${{/if}}
            
            ${{#if failure()}}
            ⚠️ The pipeline **failed** on step: ${{ github.job }} ❌
            Please review the logs and fix the issue.
            ${{/if}}
            
            Pull Request: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}